### ISSUE TITLE
Terminal errors

### ISSUE THREAD

**Issue by MarcGodard** [donejs/donejs-feathers#29]
All I get is errors!

```
Potentially unhandled rejection [7] SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Object.eval (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/can-connect-feathers/src/can-connect-feathers.js!eval:155:46)
    at fire (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.self.fireWith [as rejectWith] (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3317:7)
    at Object.<anonymous> (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3373:41)
    at fire (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.self.fireWith [as rejectWith] (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3317:7)
    at done (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:8759:14)
    at .<anonymous> (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:9123:9)
    at onload (/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/done-ssr/lib/zones/xhr.js:21:20)
Potentially unhandled rejection [8] SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Object.eval (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/can-connect-feathers/src/can-connect-feathers.js!eval:155:46)
    at fire (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.self.fireWith [as rejectWith] (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3317:7)
    at Object.<anonymous> (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3373:41)
    at fire (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3187:31)
    at Object.self.fireWith [as rejectWith] (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:3317:7)
    at done (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:8759:14)
    at .<anonymous> (file:/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/jquery/dist/jquery.js:9123:9)
    at onload (/Users/marcgodard/Desktop/AnywhereGym/AnywhereGym/node_modules/done-ssr/lib/zones/xhr.js:21:20)
```

Also you should add http://semantic-ui.com/ to the frameworks

**Comment by MarcGodard** [comment]
@marshallswain I am trying to figure out why I am getting these.

Tried to reinstall again. Same thing.

**Comment by marshallswain** [comment]
Let's do a hangout.  Send me an email and I'll reply with a link.

**Comment by marshallswain** [comment]
- Need to have a Feathers server running.
- Need to trim trailing slashes on the server URL.
- Need to install 2.0 version of the auth-component until DoneJS@0.10 is out.

**Comment by MarcGodard** [comment]
Hey @marshallswain thanks for the chat. I will be watching for your next release.

**Comment by rjpalermo1** [comment]
I'm getting the same errors.  Have no idea if your post about having the feathers server running, etc is something I need to do or something you posted for a todo.  Assuming the latter and will be looking for an update.

Thank you

**Comment by marshallswain** [comment]
That was the correct assumption. Stay tuned😎

**Comment by MarcGodard** [comment]
I cannot wait for this much longer. Can I help? I was also thinking of making an easy pagination system with doneJS. Anyway, let me know.

**Comment by marshallswain** [comment]
If you need it within the next two weeks, it would be smarter to give up on me.  :)  We're losing lots of sleep waiting for a little guy to pick his birthday.

**Comment by MarcGodard** [comment]
Hahah, I know that feeling (mine picked tomorrow but a year ago). I can wait longer than two weeks, just would love to help.

**Comment by marshallswain** [comment]
I've resolved the errors for the Basic Feathers setup.  I'm going to close this.  Adding the GUIs back in will be tracked in a separate issue.
