### ISSUE TITLE
With DoneJS alpha

### ISSUE THREAD

**Issue by MarcGodard** [donejs/donejs-feathers#31]
```
done-serve starting on http://localhost:8080
Potentially unhandled rejection [39] TypeError: Error loading "test@0.0.0#components/page-auth/page-auth.stache!steal-stache@3.0.0-pre.3#steal-stache" at file:/Users/marcgodard/Desktop/test/components/page-auth/page-auth.stache
Error loading "test@0.0.0#components/page-auth/page-auth.stache!steal-stache@3.0.0-pre.3#steal-stache" from "test@0.0.0#index.stache!done-autorender@0.9.0-pre.1#autorender" at file:/Users/marcgodard/Desktop/test/index.stache
Error evaluating test@0.0.0#models/feathers
Feathers is not a constructor
    at execute (eval at __eval (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2883:5), <anonymous>:10:18)
    at doExecute (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2155:22)
    at ensureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2202:11)
    at ensureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2186:15)
    at doEnsureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2165:15)
    at Loader.get (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2304:7)
    at getModule (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:627:24)
    at /Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:672:16
    at execute (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:1400:28)
    at linkDynamicModule (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:668:32)
Live-reload server listening on port 8012
Handled previous rejection [39] TypeError: Error loading "test@0.0.0#components/page-auth/page-auth.stache!steal-stache@3.0.0-pre.3#steal-stache" at file:/Users/marcgodard/Desktop/test/components/page-auth/page-auth.stache
Error loading "test@0.0.0#components/page-auth/page-auth.stache!steal-stache@3.0.0-pre.3#steal-stache" from "test@0.0.0#index.stache!done-autorender@0.9.0-pre.1#autorender" at file:/Users/marcgodard/Desktop/test/index.stache
Error evaluating test@0.0.0#models/feathers
Feathers is not a constructor
TypeError: Error loading "test@0.0.0#components/page-auth/page-auth.stache!steal-stache@3.0.0-pre.3#steal-stache" at file:/Users/marcgodard/Desktop/test/components/page-auth/page-auth.stache
Error loading "test@0.0.0#components/page-auth/page-auth.stache!steal-stache@3.0.0-pre.3#steal-stache" from "test@0.0.0#index.stache!done-autorender@0.9.0-pre.1#autorender" at file:/Users/marcgodard/Desktop/test/index.stache
Error evaluating test@0.0.0#models/feathers
Feathers is not a constructor
    at execute (eval at __eval (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2883:5), <anonymous>:10:18)
    at doExecute (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2155:22)
    at ensureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2202:11)
    at ensureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2186:15)
    at doEnsureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2165:15)
    at Loader.get (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2304:7)
    at getModule (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:627:24)
    at /Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:672:16
    at execute (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:1400:28)
    at linkDynamicModule (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:668:32)
TypeError: Error loading "test@0.0.0#components/page-auth/page-auth.stache!steal-stache@3.0.0-pre.3#steal-stache" at file:/Users/marcgodard/Desktop/test/components/page-auth/page-auth.stache
Error loading "test@0.0.0#components/page-auth/page-auth.stache!steal-stache@3.0.0-pre.3#steal-stache" from "test@0.0.0#index.stache!done-autorender@0.9.0-pre.1#autorender" at file:/Users/marcgodard/Desktop/test/index.stache
Error evaluating test@0.0.0#models/feathers
Feathers is not a constructor
    at execute (eval at __eval (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2883:5), <anonymous>:10:18)
    at doExecute (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2155:22)
    at ensureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2202:11)
    at ensureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2186:15)
    at doEnsureEvaluated (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2165:15)
    at Loader.get (/Users/marcgodard/Desktop/test/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:2304:7)
    at getModule (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:627:24)
    at /Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:672:16
    at execute (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:1400:28)
    at linkDynamicModule (/Users/marcgodard/Desktop/test/node_modules/steal-systemjs/dist/system.src.js:668:32)
```

**Comment by matthewp** [comment]
@chasenlehara should donejs-feathers have its own 1.0 epic? I don't think we're going to block DoneJS 1.0 for any ecosystem packages.

**Comment by marshallswain** [comment]
I don't think it really needs an epic.  I've done some initial work to upgrade it to CanJS 3.0, but when the work on DoneJS picked up again, I decided to wait until the dust settles.

**Comment by marshallswain** [comment]
I take that back.  It will need an epic to track all the changes for DoneJS@latest when it's available.

**Comment by chasenlehara** [comment]
@marshallswain I’ve removed the issues from this repo from the [DoneJS 1.0 Release epic](https://github.com/donejs/donejs/issues/703). I’ll defer to you to create the epic and organize it as you see fit. :)

**Comment by santoshanand** [comment]
is there any update on this i am getting same issue with it

**Comment by marshallswain** [comment]
Hi, @santoshanand.  The updates depend on finishing the work on DoneJS 1.0.  Once that's finished, I plan on updating this.  Thanks for checking.

**Comment by marshallswain** [comment]
`donejs-feathers@2.0.0` was just released.  I've update donejs-feathers to work with DoneJS 1.0.  For now, only the basic feathers setup is available, so a GUI must be manually added.

Please reopen if there's still an issue, but this is working for me, now.
