### ISSUE TITLE
IE 10 and IE 11 "Unable to get property 'apply' of undefined or null reference

### ISSUE THREAD

**Issue by MarcGodard** [donejs/donejs-feathers#39]
@marshallswain helped me put this code together and everything works perfectly in IE edge and Chrome and everything else I have tested so far. But IE 10 and 11 seem to have this error:

<img width="590" alt="screen shot 2017-09-14 at 10 27 44 pm" src="https://user-images.githubusercontent.com/5016637/30464096-76dd19ae-999d-11e7-8070-35e71c19beb1.png">

Any help would be appreciated considering the number of older IE browsers still out there.

Full console:
```
HTML1300: Navigation occurred.
File: 192.168.1.12:8080
WARN: can-component: Assigning a DefineMap or constructor type to the viewModel property may not be what you intended. Did you mean ViewModel instead? More info: https://canjs.com/doc/can-component.prototype.ViewModel.html
TypeError: Error loading "tx@0.0.0#components/navigation/navigation.stache!steal-stache@3.1.1#steal-stache" at http://192.168.1.12:8080/src/components/navigation/navigation.stache
Error loading "tx@0.0.0#components/navigation/navigation.stache!steal-stache@3.1.1#steal-stache" from "tx@0.0.0#index.stache!done-autorender@1.3.1#src/autorender" at http://192.168.1.12:8080/src/index.stache
Error evaluating tx@0.0.0#models/feathers-client
Unable to get property 'apply' of undefined or null reference
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'apply' of undefined or null reference",
      message: "Error loading "tx@0.0.0#components/navigation/navigation.stache!steal-stache@3.1.1#steal-stache" at http://192.168.1.12:8080/src/components/navigation/navigation.stache
Error loading "tx@0.0.0#components/navigation/navigation.stache!steal-stache@3.1.1#steal-stache" from "tx@0.0.0#index.stache!done-autorender@1.3.1#src/autorender" at http://192.168.1.12:8080/src/index.stache
Error evaluating tx@0.0.0#models/feathers-client
Unable to get property 'apply' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Error loading "tx@0.0.0#components/navigation/navigation.stache!steal-stache@3.1.1#steal-stache" at http://192.168.1.12:8080/src/components/navigation/navigation.stache
Error loading "tx@0.0.0#components/navigation/navigation.stache!steal-stache@3.1.1#steal-stache" from "tx@0.0.0#index.stache!done-autorender@1.3.1#src/autorender" at http://192.168.1.12:8080/src/index.stache
Error evaluating tx@0.0.0#models/feathers-client
Unable to get property 'apply' of undefined or null reference
   at baseMixin (Function code:138:3)
   at Anonymous function (Function code:156:5)
   at configure (Function code:152:5)
   at execute (eval code:20:7)
   at doExecute (http://192.168.1.12:8080/node_modules/steal/steal.js:2158:7)
   at ensureEvaluated (http://192.168.1.12:8080/node_modules/steal/steal.js:2205:5)
   at ensureEvaluated (http://192.168.1.12:8080/node_modules/steal/steal.js:2189:9)
   at doEnsureEvaluated (http://192.168.1.12:8080/node_modules/steal/steal.js:2168:5)
   at Loader.prototype.get (http://192.168.1.12:8080/node_modules/steal/steal.js:2308:7)
   at getModule (http://192.168.1.12:8080/node_modules/steal/steal.js:4036:7)",
      Symbol()_j.6jydyzb52jv: undefined,
      Symbol()_l.6jydyzb52jv: undefined,
      Symbol()_m.6jydyzb52jv: undefined,
      Symbol()_n.6jydyzb52jv: undefined,
      Symbol()_o.6jydyzb52jv: undefined,
      Symbol()_p.6jydyzb52jv: undefined,
      Symbol()_q.6jydyzb52jv: undefined,
      Symbol(should not be considered a local binding)_i.6jydyzb52jv: undefined,
      Symbol(super this bound)_k.6jydyzb52jv: undefined,
      Symbol(var used to be block scoped)_h.6jydyzb52jv: undefined
   }
```
feathers-client.js
```
import jQuery from 'jquery';
import feathers from 'feathers/client'
import rest from 'feathers-rest/client'
import auth from 'feathers-authentication-client'
import hooks from 'feathers-hooks'
import loader from '@loader'

const feathersClient = feathers()
  .configure(rest(loader.serviceBaseURL).jquery(jQuery))
  .configure(hooks())
  .configure(auth({
    storage: window.localStorage
  }))

export default feathersClient
```

Feathers Versions:
```
    "feathers": "^2.2.0",
    "feathers-authentication-client": "^0.3.3",
    "feathers-hooks": "^2.0.2",
    "feathers-rest": "^1.8.0",
    "feathers-socketio": "^2.0.0",
```

**Comment by marshallswain** [comment]
@MarcGodard You can see the browser support at the feathers-client page: https://github.com/feathersjs/feathers-client

If you need more support for older browsers, you may need to follow the docs for using a direct connection: https://docs.feathersjs.com/api/rest.html#direct-connection.  can-connect Ajax requests work quite well with Feathers out of the box.

**Comment by marshallswain** [comment]
You might also try loading the babel-polyfill module before loading feathers-client.  I'm going to close this since the donejs-feathers module doesn't have any influence over browser support with IE.
